# Generated by Django 2.2.28 on 2023-06-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('no_of_pack', models.IntegerField()),
                ('exp', models.DateField()),
                ('status', models.CharField(choices=[('i', 'in_stock'), ('o', 'outof_stock')], default='i', max_length=1)),
            ],
        ),
    ]
